### ISSUE TITLE
Cannot download.

### ISSUE THREAD

**Issue by Overload119** [bmulvihill/rufo-atom#1]
When trying to download from Atom.

`Unable to download https://www.atom.io/api/packages/rufo-atom/versions/0.0.1/tarball: 400 Bad Request Repository inaccessible`

![image](https://user-images.githubusercontent.com/1012072/31313882-65af5e52-aba5-11e7-9275-8a99106679a4.png)

**Comment by bmulvihill** [comment]
@Overload119 I just attempted this and was able to download the package, can you try again?

**Comment by Overload119** [comment]
Yup, tried again and same error.
I would suggest re-publishing to Atom.

I can also validate this by trying to access the URL directly in Chrome:

![image](https://user-images.githubusercontent.com/1012072/31322628-37f2cd18-ac50-11e7-91b8-a7f878c1d722.png)

**Comment by bmulvihill** [comment]
@Overload119 I republished v0.1.0
